permissions:
  contents: read

name: machete-action
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  machete:
    name: 'cargo-machete for ${{ github.event_name }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: dtolnay/rust-toolchain@a54c7afa936fefeb4456b2dd8068152669aa8203 # master
        with:
          components: clippy
          targets: x86_64-unknown-linux-gnu
          toolchain: nightly
      - run: cargo install cargo-machete
      - run: cargo machete --with-metadata
