permissions:
  contents: read

name: machete-action
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  machete:
    name: 'cargo-machete for ${{ github.event_name }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - uses: dtolnay/rust-toolchain@888c2e1ea69ab0d4330cbf0af1ecc7b68f368cc1 # master
        with:
          components: clippy
          targets: x86_64-unknown-linux-gnu
          toolchain: nightly
      - run: cargo install cargo-machete
      - run: cargo machete --with-metadata
