permissions:
  contents: read

name: test-action
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  test:
    name: 'Test for ${{ github.event_name }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: dtolnay/rust-toolchain@56f84321dbccf38fb67ce29ab63e4754056677e0 # master
        with:
          components: clippy
          targets: x86_64-unknown-linux-gnu
          toolchain: nightly
      - run: |
          cargo test --workspace --target x86_64-unknown-linux-gnu --all
