permissions:
  contents: read

name: test-action
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  test:
    name: 'Test for ${{ github.event_name }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: dtolnay/rust-toolchain@7b1c307e0dcbda6122208f10795a713336a9b35a # master
        with:
          components: clippy
          targets: x86_64-unknown-linux-gnu
          toolchain: nightly
      - run: |
          cargo test --workspace --target x86_64-unknown-linux-gnu --all
