permissions:
  contents: read

name: test-action
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  test:
    name: 'Test for ${{ github.event_name }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: dtolnay/rust-toolchain@888c2e1ea69ab0d4330cbf0af1ecc7b68f368cc1 # master
        with:
          components: clippy
          targets: x86_64-unknown-linux-gnu
          toolchain: nightly
      - run: |
          cargo test --workspace --target x86_64-unknown-linux-gnu --all
